# Generated by Django 2.0.1 on 2018-01-24 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
    ]
