# Generated by Django 2.0.2 on 2018-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_auto_20180127_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='赞同数'),
        ),
    ]
