# Generated by Django 2.0.2 on 2018-02-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_auto_20180217_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-updated',), 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
