# Generated by Django 2.0.2 on 2018-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_auto_20180217_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
