# Generated by Django 2.0.2 on 2018-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0007_auto_20180217_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='flows',
            field=models.PositiveIntegerField(default=0, verbose_name='关注'),
        ),
        migrations.AddField(
            model_name='question',
            name='flows',
            field=models.PositiveIntegerField(default=0, verbose_name='关注'),
        ),
        migrations.AddField(
            model_name='topic',
            name='flows',
            field=models.PositiveIntegerField(default=0, verbose_name='关注'),
        ),
    ]
