# Generated by Django 2.0.2 on 2018-02-11 22:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0004_auto_20180211_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('vote_type', models.CharField(max_length=10)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.Answer', verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
