# Generated by Django 2.0.2 on 2018-02-21 12:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='Question.Answer', verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏问题',
                'verbose_name_plural': '用户收藏问题',
            },
        ),
        migrations.CreateModel(
            name='UserFlowQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_operation', to='Question.Question', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_question', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注问题',
                'verbose_name_plural': '用户关注问题',
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('vote_type', models.CharField(choices=[('up', '支持'), ('down', '反对')], max_length=10)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_operation', to='Question.Answer', verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户赞同反对',
                'verbose_name_plural': '用户赞同反对',
            },
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='userflowquestion',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'answer')},
        ),
    ]
