# Generated by Django 2.0.2 on 2018-02-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountOperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservote',
            options={'verbose_name': '用户赞同反对', 'verbose_name_plural': '用户赞同反对'},
        ),
        migrations.AlterField(
            model_name='uservote',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_operation', to='Question.Answer', verbose_name='回答'),
        ),
    ]
