# Generated by Django 2.0.2 on 2018-02-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountOperation', '0002_auto_20180211_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='answers',
            new_name='answer',
        ),
    ]
