# Generated by Django 2.0.2 on 2018-02-11 22:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_auto_20180211_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccountOperation', '0003_auto_20180211_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'answer', 'vote_type')},
        ),
    ]
