# Generated by Django 2.0.2 on 2018-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountOperation', '0004_auto_20180211_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='vote_type',
            field=models.CharField(choices=[('up', '支持'), ('down', '反对')], max_length=10),
        ),
    ]
