# Generated by Django 2.0.2 on 2018-02-17 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_auto_20180217_1149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccountOperation', '0005_auto_20180212_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'answer')},
        ),
    ]
