# Generated by Django 2.0.2 on 2018-02-18 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0008_auto_20180218_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccountOperation', '0006_auto_20180217_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlowQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_operation', to='Question.Question', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_question', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注问题',
                'verbose_name_plural': '用户关注问题',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userflowquestion',
            unique_together={('user', 'question')},
        ),
    ]
